vile:
  ignore:
    - appveyor.yml
    - coverage
    - coffeelint.json
    - .ackrc
    - .babelrc
    - .build
    - .npmignore
    - .travis.yml
    - .vim.custom
    - node_modules
    - lib
    - tags
    - .test
    - .ctags
    - .git
    - circle.yml
    - .editorconfig
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - tags
    - tmp
    - tsconfig.json
    - tslint.json
    - tsd.json
    - "/lib"
    - vendor
    - README.md
    - typings
    - .vile.yml
